spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/provadb
    username:
    password:
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop
---
environment: test
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username:
    password:
    driver-class-name:  org.h2.Driver
  jpa:
    database: h2
  h2:
    console:
      enabled: true